### ISSUE TITLE
Install Nano - all docker containers

### ISSUE THREAD

**Issue by treg** [BurningFlipside/DevSandbox#25]
there should be at least one text editor installed on containers for development

**Comment by russelltsherman** [comment]
I would vote not to include editors within the container images by default.
the idea of a container is that it only includes the minimum set of applications it requires to function under normal circumstances.

while working on the BF codebase you should almost never need to enter the containers to make changes.

As a developer can attach a shell session to any container and install any applications you would like for whatever purpose you see fit.  Those changes will persist for the lifetime of the container.
